// Command gendocs regenerates docs/cli.md — the single-file CLI reference —
// from the cobra command tree. Run from the repo root:
//
//	go run ./tools/gendocs
//
// The reference is generated; manual edits are overwritten. CI regenerates
// and diffs the file so help-text drift fails the build instead of shipping
// stale documentation.
//
// The markdown is rendered here directly from cobra's public API rather than
// via spf13/cobra/doc: that package pulls in md2man and yaml modules for man
// and yaml output this tool never produces (PLAN.md design principle 4,
// minimal dependencies).
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/MikkoP88/s3-bucket-browser/internal/cli"
	"github.com/spf13/cobra"
)

const header = `# s3b CLI reference

<!-- Generated by "go run ./tools/gendocs" from the cobra command tree. -->
<!-- Do not edit by hand: regenerate with the command above instead.       -->

` + "`s3b`" + ` is the command-line face of S3 Bucket Browser. Run it without
arguments to launch the desktop GUI; run it with any argument to use the CLI
described here. The same engine backs both.

- **Global flags** — every command accepts the persistent flags documented on
  [` + "`s3b`" + `](#s3b) itself (` + "`--profile`" + `, ` + "`--json`" + `, ` + "`--verbose`" + `, ` + "`--timeout`" + `,
  credential/addressing overrides).
- **S3 URIs** — commands address storage as ` + "`s3://bucket/prefix/`" + `; a trailing
  slash marks a folder/prefix.
- **Environment** — ` + "`S3B_CONFIG`" + ` (config directory), ` + "`S3B_PROFILE`" + ` (default
  profile), ` + "`S3B_ACCESS_KEY`" + ` / ` + "`S3B_SECRET_KEY`" + ` (credential fallback),
  ` + "`S3B_NO_KEYRING=1`" + ` (keep secrets in the config file instead of the OS
  keyring).
- **Exit codes** — ` + "`0`" + ` success, ` + "`1`" + ` operation failure, ` + "`2`" + ` usage/config
  error, ` + "`3`" + ` unexpected error.
- **Safety ladder** — destructive operations count first and act second:
  prefix deletes over 50 objects require ` + "`--force`" + `, non-empty bucket removal
  requires ` + "`--force`" + `, permanent version destruction is L3.

`

func main() {
	root := cli.NewRoot()
	// Materialize the auto-added commands (help, completion) so they get
	// documented sections like everything else.
	root.InitDefaultHelpCmd()
	root.InitDefaultCompletionCmd()
	// cobra keeps the help command unexported; grab its pointer by name so
	// documented() can include it (IsAvailableCommand() alone skips it).
	for _, sub := range root.Commands() {
		if sub.Name() == "help" {
			helpCmd = sub
		}
	}

	var b strings.Builder
	b.WriteString(header)
	b.WriteString("## Index\n\n")
	writeIndex(&b, root, 0)
	b.WriteString("\n---\n\n")
	writeCmd(&b, root)

	if err := os.MkdirAll("docs", 0o755); err != nil {
		fatal("mkdir docs: %v", err)
	}
	if err := os.WriteFile("docs/cli.md", []byte(b.String()), 0o644); err != nil {
		fatal("write docs/cli.md: %v", err)
	}
	fmt.Printf("wrote docs/cli.md (%d bytes)\n", b.Len())
}

// helpCmd is the auto-added "help" command (set in main).
var helpCmd *cobra.Command

// documented reports whether sub earns a section: every available command
// plus the auto-added help command (cobra's own docs link to it).
func documented(sub *cobra.Command) bool {
	return sub.IsAvailableCommand() || sub == helpCmd
}

// writeCmd writes the section for cmd, then recurses parents-before-children
// so every SEE ALSO link has a target.
func writeCmd(w *strings.Builder, cmd *cobra.Command) {
	name := cmd.CommandPath()
	fmt.Fprintf(w, "## %s\n\n", name)
	fmt.Fprintf(w, "%s\n\n", cmd.Short)
	if len(cmd.Long) > 0 {
		w.WriteString("### Synopsis\n\n")
		fmt.Fprintf(w, "%s\n\n", cmd.Long)
	}
	if cmd.Runnable() {
		fmt.Fprintf(w, "```\n%s\n```\n\n", cmd.UseLine())
	}
	if cmd.HasExample() {
		w.WriteString("### Examples\n\n")
		fmt.Fprintf(w, "```\n%s\n```\n\n", cmd.Example)
	}
	if flags := cmd.LocalFlags(); flags.HasAvailableFlags() {
		w.WriteString("### Options\n\n```\n")
		fmt.Fprintf(w, "%s\n", flags.FlagUsages())
		w.WriteString("```\n\n")
	}
	if flags := cmd.InheritedFlags(); flags.HasAvailableFlags() {
		w.WriteString("### Options inherited from parent commands\n\n```\n")
		fmt.Fprintf(w, "%s\n", flags.FlagUsages())
		w.WriteString("```\n\n")
	}
	if seeAlso(w, cmd) {
		w.WriteString("\n")
	}

	for _, sub := range cmd.Commands() {
		if !documented(sub) {
			continue
		}
		writeCmd(w, sub)
	}
}

// seeAlso writes the SEE ALSO block (parent first, then children) and
// reports whether one was written.
func seeAlso(w *strings.Builder, cmd *cobra.Command) bool {
	var links []string
	if cmd.HasParent() {
		p := cmd.Parent()
		links = append(links, fmt.Sprintf("* [%s](#%s)", p.CommandPath(),
			anchorName(p.CommandPath())))
	}
	for _, sub := range cmd.Commands() {
		if !documented(sub) {
			continue
		}
		links = append(links, fmt.Sprintf("* [%s](#%s)", sub.CommandPath(),
			anchorName(sub.CommandPath())))
	}
	if len(links) == 0 {
		return false
	}
	w.WriteString("### SEE ALSO\n\n")
	w.WriteString(strings.Join(links, "\n"))
	w.WriteString("\n")
	return true
}

// writeIndex lists the command tree as links to the generated sections.
func writeIndex(w *strings.Builder, cmd *cobra.Command, depth int) {
	for _, sub := range cmd.Commands() {
		if !documented(sub) {
			continue
		}
		fmt.Fprintf(w, "%s- [%s](#%s) — %s\n", strings.Repeat("  ", depth),
			sub.CommandPath(), anchorName(sub.CommandPath()), sub.Short)
		writeIndex(w, sub, depth+1)
	}
}

// anchorName turns a command path into its markdown in-page anchor.
func anchorName(path string) string {
	return strings.ReplaceAll(path, " ", "-")
}

func fatal(format string, a ...any) {
	fmt.Fprintf(os.Stderr, "gendocs: "+format+"\n", a...)
	os.Exit(1)
}
